config/routes.rb
Rails.application.routes.draw do
  get "/" => "home#top"

  resources :tasks do
    resources :entries, only: [:new, :create, :edit, :update]
  end


  # workerに関するルーティング
  get "workers/top" => "workers#top"

  # ログインフォームとログイン処理
  get "workers/login" => "workers#login_form"
  post "workers/login" => "workers#login"

  # 従業員側から、シフトのやり取りをする管理者を検索し、紐づけできるように
  # するため、管理者検索フォームを実装する
  get "workers/search_owner" => "workers#search_owner"

  # ログアウトする。workerでもownerでも処理は同じであるため、
  # workersコントローラのアクションを使う
  post "logout" => "workers#logout"

  resources :workers, only: [:show, :new, :create, :edit, :update, :destroy]



  # ownerに関するルーティング
  get "owners/top" => "owners#top"

  # ログインフォームとログイン処理
  get "owners/login" => "owners#login_form"
  post "owners/login" => "owners#login"

  resources :owners, only: [:show, :new, :create, :edit, :update, :destroy]


  # owner_workersに関するルーティング
  get "owner_workers" => "owner_workers#index"
  post "owner_workers/create/:request_id" => "owner_workers#create"
  post "owner_workers/:id/destroy" => "owner_workers#destroy"


  # 従業員から管理者に対するユーザー紐づけリクエスト"request"
  # に関するルーティング
  get "requests" => "requests#index"
  post "requests/:owner_id" => "requests#create"
  post "requests/:id/destroy" => "requests#destroy"

end

app/models/owner.rb
class Owner < ApplicationRecord
  has_secure_password

  has_many :owner_workers, dependent: :destroy
  has_many :workers, through: :owner_workers

  has_many :tasks, dependent: :destroy
  has_many :requests, dependent: :destroy

  validates :name, {presence: true, length: {maximum: 14}}
  validates :email, {presence: true, uniqueness: true,
                     length: {maximum: 254}}
  validates :userid, {presence: true,
                      uniqueness: true,
                      length: {minimum: 4, maximum: 16}}
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
  before_action :authenticate_user, {only: [:show, :edit, :update, :destroy]}
  before_action :forbid_login_user, {only: [:top, :new, :create, :login_form, :login]}
  before_action :ensure_correct_owner, {only: [:show, :edit, :update, :destroy]}

  def top
  end

  def show
    @owner = Owner.find(params[:id])
  end

  def new
    @owner = Owner.new
  end

  def create
    @owner = Owner.new(owner_params)
    if @owner.save
      # アカウント作成が成功したらそのままログイン状態にする。
      session[:user_id] = @owner.id
      session[:user_type] = "owner"

      # フラッシュメッセージを表示する。
      flash[:notice] = "アカウントを作成しました"

      # ユーザーページへリダイレクトする。
      redirect_to(@owner)
    else
      # 失敗すると再度登録フォームを表示する。
      render("owners/new")
    end
  end

  def edit
    @owner = Owner.find(params[:id])
    @edit_password_message = "パスワードを変更する方は以下に新しいパスワードを入力"
  end

  def update
    @owner = Owner.find(params[:id])

    if @owner.update(owner_params)
      flash[:notice] = "ユーザー情報を編集しました"
      redirect_to(@owner)
    else
      render("owners/edit")
    end
  end

  def login_form
  end

  def login
    # 従業員データの中から、ユーザーIDが一致するものを探す
    @owner = Owner.find_by(userid: params[:userid])

    if @owner && @owner.authenticate(params[:password])
      # ログイン状態にする
      session[:user_id] = @owner.id
      session[:user_type] = "owner"

      # フラッシュメッセージを表示する
      flash[:notice] = "ログインしました"

      # 募集中一覧へリダイレクトする
      redirect_to(tasks_path)
    else
      @error_message = "ユーザーIDまたはパスワードが間違っています"
      render("owners/login_form")
    end
  end

  def logout
    session[:user_id] = nil
    session[:user_type] = nil
    flash[:notice] = "ログアウトしました"
    redirect_to("/")
  end

  def destroy
    @owner = Owner.find(params[:id])
    @owner.destroy
    flash[:notice] = "アカウントを削除しました"
    redirect_to("/")
  end

  private
  def owner_params
    params.require(:owner).permit(:name, :userid, :email, :password, :password_confirmation)
  end

  def ensure_correct_owner
    if !(@current_user.class == Owner && @current_user.id == params[:id].to_i)
      flash[:notice] = "権限がありません"
      redirect_to("/")
    end
  end
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/views/owners/_form.html.erb
<div class="form-error">
  <% @owner.errors.full_messages.each do |message| %>
    <%= message %><br>
  <% end %>
</div>

<div class="form-wrapper">
  <%= form_with(model: @owner, local: true) do |form| %>
    <p>名前</p>
    <p>※氏名や店名など</p>
    <%= form.text_field :name %><br>

    <p>ユーザーID（4文字以上16文字以内）</p>
    <%= form.text_field :userid %><br>

    <p>メールアドレス</p>
    <%= form.text_field :email %><br>

    <!-- フォームがeditに使われる時だけ表示するメッセージ -->
    <% if @edit_password_message %>
      <br><p><%= @edit_password_message %></p>
    <% end %>

    <p>パスワード</p>
    <%= form.password_field :password %><br>

    <p>パスワード（確認）</p>
    <%= form.password_field :password_confirmation %><br>

    <%= form.submit "決定", class:"btn form-btn" %>
  <% end %>
</div>

app/views/owners/edit.html.erb
<div class="main">
  <div class="container">
    <div class="heading">
      ユーザー情報の編集
    </div>
    <%= render("form") %>
    <%= link_to("戻る", owner_path(@owner), {class: "btn return-btn"}) %>
  </div>
</div>

app/views/owners/login_form.html.erb
<div class="main">
  <div class="container">
    <div class="heading">
      ログイン（管理者）
    </div>
    <% if @error_message %>
    <div class="form-error">
      <%= @error_message %>
    </div>
    <% end %>
    <div class="form-wrapper">
      <%= form_with(url: "/owners/login", local: true) do |form| %>
        <p>ユーザーID</p>
        <%= form.text_field :userid %><br>

        <p>パスワード</p>
        <%= form.password_field :password %><br>

        <%= form.submit "ログイン", class: "btn form-btn" %>
      <% end %>
    </div>
    <%= link_to("戻る", "/owners/top", {class: "btn return-btn"}) %>
  </div>
</div>

app/views/owners/new.html.erb
<div class="main">
  <div class="container">
    <div class="heading">
      アカウント作成（管理者）
    </div>
    <%= render("form") %>
    <%= link_to("戻る", "/owners/top", {class: "btn return-btn"}) %>
  </div>
</div>

app/views/owners/show.html.erb
<div class="main">
  <div class="container">
    <div class="heading">
      マイページ
    </div>
    <div class="mypage-wrapper">
      <p>名前：<%= @owner.name %></p>
      <p>ユーザーID：<%= @owner.userid %></p>
      <p>メールアドレス：<%= @owner.email %></p>
    </div>
    <div class="edit-profile-btn-wrapper">
      <%= link_to("ユーザー情報の編集", edit_owner_path(@owner), {class: "btn edit-profile-btn"}) %>
      <%= link_to("退会する", owner_path(@owner), method: :delete,
                  data: {confirm: "退会すると、シフトのデータは削除されます。よろしいですか？"},
                  class: "btn edit-profile-btn") %>
    </div>
  </div>
</div>

app/views/owners/top.html.erb
<div class="main">
  <div class="container">
    <div class="heading">
      管理者
    </div>
    <div class="entrance-wrapper">
      <ul class="top-btns">
        <li><%= link_to("アカウント作成", new_owner_path, {class: "btn large-btn"}) %></li>
        <li><%= link_to("ログイン", "/owners/login", {class: "btn large-btn"}) %></li>
        <%= link_to("TOPへ戻る", "/", {class: "btn large-btn"}) %>
      </ul>
    </div>
  </div>
</div>