config/routes.rb
Rails.application.routes.draw do
  get "/" => "home#top"

  resources :tasks do
    resources :entries, only: [:new, :create, :edit, :update]
  end


  # workerに関するルーティング
  get "workers/top" => "workers#top"

  # ログインフォームとログイン処理
  get "workers/login" => "workers#login_form"
  post "workers/login" => "workers#login"

  # 従業員側から、シフトのやり取りをする管理者を検索し、紐づけできるように
  # するため、管理者検索フォームを実装する
  get "workers/search_owner" => "workers#search_owner"

  # ログアウトする。workerでもownerでも処理は同じであるため、
  # workersコントローラのアクションを使う
  post "logout" => "workers#logout"

  resources :workers, only: [:show, :new, :create, :edit, :update, :destroy]



  # ownerに関するルーティング
  get "owners/top" => "owners#top"

  # ログインフォームとログイン処理
  get "owners/login" => "owners#login_form"
  post "owners/login" => "owners#login"

  resources :owners, only: [:show, :new, :create, :edit, :update, :destroy]


  # owner_workersに関するルーティング
  get "owner_workers" => "owner_workers#index"
  post "owner_workers/create/:request_id" => "owner_workers#create"
  post "owner_workers/:id/destroy" => "owner_workers#destroy"


  # 従業員から管理者に対するユーザー紐づけリクエスト"request"
  # に関するルーティング
  get "requests" => "requests#index"
  post "requests/:owner_id" => "requests#create"
  post "requests/:id/destroy" => "requests#destroy"

end

app/models/task.rb
class Task < ApplicationRecord
  has_many :entries, dependent: :destroy

  validates :owner_id, {presence: true}
  validates :title, {presence: true, length: {maximum: 30}}
  validates :from_date, {presence: true}
  validates :to_date, {presence: true}
  validates :deadline, {presence: true}
  validates :comment, {length: {maximum: 200}}

  # 設定が不適切だと、そのメッセージを配列にして返す
  def task_setting_errors
    error_messages = []
    # タイトル、日付のどれかがnilになっている
    if self.title == nil || self.from_date == nil || self.to_date == nil
      error_messages.push("必須項目が未入力です")
    else
      # to_dateがfrom_fateより前になっている
      if self.to_date < self.from_date
        error_messages.push("対象期間の設定が不整合です")
      end
      # 締め切りが今日より前になっている
      if self.deadline < Date.today
        error_messages.push("締め切りを今日より前の日付に設定することはできません")
      end
    end

    if error_messages.empty?
      return nil
    else
      return error_messages
    end
  end

  # taskには、何日から何日までの希望が欲しいかの情報が含まれる。その期間を配列で渡す。
  def get_days
    # 日数を取得する
    num_of_days = (self.to_date - self.from_date).to_i
    # 日数分、日にちを加算しながら配列に格納する
    days = [self.from_date]
    for i in 1..num_of_days do
      days.push(self.from_date + i)
    end
    return days
  end

  # キーに従業員のid、バリューに日数分のentryの配列を持ったハッシュを取得する
  def get_entries_table
    # taskの管理者を探す
    owner = Owner.find(self.owner_id)
    # 今回のtaskに該当する期間の日付を配列で取得する
    days = self.get_days

    entries_table = {}

    #この管理者の従業員のすべてに対し
    owner.workers.each do |worker|
      # この従業員が持つentryの中から、今回のtaskに関するものを取り出す
      entries = worker.entries.where(task_id: self.id)
      # 存在すれば
      if entries.empty? == false
        # キーが従業員のid、バリューが配列である要素をentries_tableに追加する。
        entries_table[worker.id] = []
        days.each_with_index do |day, i|
          # 該当の日付の物を取得する
          entry = entries.find_by(day: day)
          # インスタンスメソッド"time_to_string"(models\entry.rb)
          # 時間をhh:mm形式の文字列に変換して追加する。
          entries_table[worker.id]
              .push([entry.id.to_s, entry.time_to_string])
        end
      end
    end
    return entries_table
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user
  before_action :ensure_correct_user_for_show, {only: [:show]}
  before_action :permit_only_owner, {only: [:new, :create]}
  before_action :ensure_correct_owner, {only: [:edit, :update, :destroy]}


  def index
    # 管理者ユーザーの場合、自らのtasksを表示する。
    if @current_user.class == Owner
      @tasks = @current_user.tasks.order(:deadline)

    # 従業員ユーザーの場合、関係を持つ管理者のtasksを表示する。
    elsif @current_user.class == Worker
      @owners = @current_user.owners
      @tasks = []
      @owners.each do |owner|
        owner.tasks.order(:deadline).each do |task|
          @tasks.push(task)
        end
      end
    end
  end

  def show
    @task = Task.find(params[:id])
    @owner = Owner.find(@task.owner_id)
    @workers = @owner.workers.order(:userid)
    # インスタンスメソッド"get_days"(models\task.rb)
    # taskには、何日から何日までの希望が欲しいかの情報が含まれる。その期間の日付を配列で渡す。
    @days = @task.get_days
    @entries_table = {}

    # このtaskに属するentryが存在する場合
    if @task.entries.empty? == false
      # インスタンスメソッド"get_entries_table"(models\task.rb)
      # キーに従業員の名前、バリューに日数分の出勤可能時間の配列を持ったハッシュを取得する。
      @entries_table = @task.get_entries_table
    end

    # 指定されたフォーマットによって処理を変える。
    respond_to do |format|
      # htmlなら、通常通りテンプレートを表示する。
      format.html
      # xlsxなら、ファイルをダウンロードさせる。
      # Content-Dispositionで、ウェブページ（又はその一部）として表示するか、ダウンロードファイル
      # とするか選べる。attachmentを指定したので、ダウンロードファイルとなる。
      # ファイル名は"今日の日付.xlsx"。
      format.xlsx do
        response.headers['Content-Disposition'] = "attachment; filename=#{Date.today}.xlsx"
      end
    end
  end

  def new
    @task = Task.new
  end

  def edit
    @task = Task.find(params[:id])
  end

  def create
    @task = Task.new(task_params)
    @task.owner_id = @current_user.id

    # インスタンスメソッド"task_setting_errors"(models\task.rb)
    # 設定が不適切だと、そのメッセージが配列になって返ってくる。
    if @error_messages = @task.task_setting_errors
      render("tasks/new")
    elsif @task.save
      flash[:notice] = "投稿しました"
      redirect_to(tasks_path)
    else
      render("tasks/new")
    end

  end

  def update
    @task = Task.find(params[:id])

    # 編集はコメントに対してしか受け付けない。
    if @task.update(edit_task_params)
      flash[:notice] = "編集しました"
      redirect_to(@task)
    else
      render("tasks/edit")
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    redirect_to(tasks_path)
  end

  def task_params
    params.require(:task).permit(:title, :from_date, :to_date, :deadline, :comment)
  end

  def edit_task_params
    params.require(:task).permit(:comment)
  end

  private

  def ensure_correct_owner
    @task = Task.find(params[:id])
    if !(@current_user.class == Owner && @task.owner_id == @current_user.id)
      flash[:notice] = "権限がありません"
      redirect_to("/")
    end
  end

  # show用のユーザー認証。
  def ensure_correct_user_for_show
    @task = Task.find(params[:id])
    # 管理者としてログインしている場合
    if @current_user.class == Owner
      # 自分の作成したtask出なければ閲覧できない。
      if @current_user.id != @task.owner_id
        flash[:notice] = "権限がありません"
        redirect_to("/")
      end
    # 従業員としてログインしている場合
    else
      # そのtaskの管理者と自分がowner_workerの関係になければ閲覧できない。
      @owner_worker = OwnerWorker.find_by(owner_id: @task.owner_id, worker_id: @current_user.id)
      if @owner_worker == nil
        flash[:notice] = "権限がありません"
        redirect_to("/")
      end
    end
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/edit.html.erb
<div class="main">
  <div class="container">
    <div class="heading">
      <%= @task.title %>
    </div>
    <div class="task-wrapper">
      <p>期間：<%= Entry.date_y_to_string(@task.from_date) %>～<%= Entry.date_y_to_string(@task.to_date) %></p>
      <p>締め切り：<%= Entry.date_y_to_string(@task.deadline) %></p>
    </div>
    <div class="form-error">
      <% @task.errors.full_messages.each do |message| %>
        <%= message %><br>
      <% end %>
    </div>
    <div class="form-wrapper">
      <%= form_with(model: @task, local: true) do |form| %>
        <p>コメント（200文字以内）</p>
        <%= form.text_area :comment, size:("40x5") %><br>

        <%= form.submit "更新する", {class: "btn form-btn"} %>
      <% end %>
    </div>
    <%= link_to("募集詳細に戻る", task_path(@task), {class: "btn return-btn"}) %>
  </div>
</div>

app/views/tasks/index.html.erb
<div class="main">
  <div class="container">
    <div class="heading">
      募集中一覧
    </div>
    <% if @current_user.class == Owner %>
      <div class="new-task-btn-wrapper">
        <%= link_to("新規作成", new_task_path, class:"btn new-task-btn") %>
      </div>
    <% end %>
    <div class="tasks-index-wrapper">
      <% if @tasks.empty? %>
        <p>
          募集中の物はありません
        </p>
      <% else %>
        <% @tasks.each do |task| %>
          <div class="task-wrapper">
            <%= link_to(task.title, task_path(task), {class: "task-title"}) %>
            <p>作成者：<%= Owner.find(task.owner_id).name %></p>
            <p>期間：<%= Entry.date_y_to_string(task.from_date) %>～<%= Entry.date_y_to_string(task.to_date) %></p>
            <p>締め切り：<%= Entry.date_y_to_string(task.deadline) %></p>
            <p>コメント：<%= task.comment %></p>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/tasks/new.html.erb
<div class="main">
  <div class="container">
    <div class="heading">
      シフト募集の新規作成
    </div>
    <div class="form-error">
      <!-- validateによるエラーメッセージの表示 -->
      <% @task.errors.full_messages.each do |message| %>
        <%= message %><br>
      <% end %>
      <!-- コントローラで独自に設定したエラーメッセージの表示 -->
      <% if @error_messages %>
        <% @error_messages.each do |message| %>
          <%= message %><br>
        <% end %>
      <% end %>
    </div>
    <div class="form-wrapper">
      <%= form_with(model: @task, local: true) do |form| %>
        <p>タイトル（30文字以内）</p>
        <%= form.text_field :title, size: 30 %><br>

        <p>期間</p>
        <%= form.date_field :from_date, class: "date-form" %>から<%= form.date_field :to_date, class:"date-form" %>まで

        <p>締め切り</p>
        <%= form.date_field :deadline %><br>

        <p>コメント（任意、200文字以内）</p>
        <%= form.text_area :comment, size:("40x5") %><br>

        <p>コメント以外は後から編集できません。内容をよくご確認ください。</p>
        <%= form.submit "投稿", class: "btn form-btn" %><br>
      <% end %>
    </div>
    <%= link_to("募集中一覧へ戻る", tasks_path, class: "btn return-btn") %>
  </div>
</div>

app/views/tasks/show.html.erb
<div class="main">
  <div class="container">
    <div class="heading">
      <%= @task.title %>
    </div>
    <div class="task-wrapper">
      <p>作成者：<%= @owner.name %></p>
      <p>期間：<%= Entry.date_y_to_string(@task.from_date) %>～<%= Entry.date_y_to_string(@task.to_date) %></p>
      <p>締め切り：<%= Entry.date_y_to_string(@task.deadline) %></p>
      <p>コメント：<%= @task.comment %></p>
      <p>希望登録数：<%= @entries_table.length %>（従業員数：<%= @workers.length %>）</p>
      <div class="edit-task-btn-wrapper">
      <% if @current_user.class == Owner %>
        <%= link_to("コメントを編集する", edit_task_path(@task), class: "btn edit-task-btn") %>
        <%= link_to("削除する", task_path(@task),
                            method: :delete,
                            data: {confirm: "本当に削除してよろしいですか？"},
                            class: "btn edit-task-btn")%>
      <% else %>
        <%= link_to("希望を登録する", new_task_entry_path(@task), class: "btn edit-task-btn") %>
      <% end %>
      </div>
    </div>
    <div class="task-entries-wrapper">
      <div class="second-heading">
        従業員の希望
      </div>
      <%= link_to("Excelファイルでダウンロード", task_path(@task, format: :xlsx), class:"btn excel-btn") %>
      <div class="task-entries-table">
        <table>
          <tr>
            <th>名前</th>
            <% @days.each do |day| %>
            <th><%= Entry.date_to_string(day) %></th>
            <% end %>
          </tr>
          <% @workers.each do |worker| %>
            <!-- ハッシュの要素は
                 worker.id => [["entry_id", "時間"], ["entry_id","時間"]...]
                 となっており、バリューの配列の中身はtaskの日数分ある -->
          <tr>
            <td><%= worker.name %></td>
            <!-- entries_tableにこの従業員のentryが存在すれば -->
            <% if entries = @entries_table[worker.id] %>
              <% (0..@days.length-1).each do |i| %>
                <!-- ログイン中のユーザーのデータなら、編集へのリンクとなる -->
                <% if @current_user.class == Worker && worker.id == @current_user.id %>
                  <td class="my-entry"><%= link_to("#{entries[i][1]}",
                                  "/tasks/#{@task.id}/entries/#{entries[i][0].to_i}/edit") %></td>
                <% else %>
                  <td><%= entries[i][1] %></td>
                <% end %>
              <% end %>
            <% else %>
              <% (0..@days.length-1).each do |i| %>
                <!-- 空のセルを生成　-->
                <td></td>
              <% end %>
            <% end %>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>