config/routes.rb
Rails.application.routes.draw do
  get "/" => "home#top"

  resources :tasks do
    resources :entries, only: [:new, :create, :edit, :update]
  end


  # workerに関するルーティング
  get "workers/top" => "workers#top"

  # ログインフォームとログイン処理
  get "workers/login" => "workers#login_form"
  post "workers/login" => "workers#login"

  # 従業員側から、シフトのやり取りをする管理者を検索し、紐づけできるように
  # するため、管理者検索フォームを実装する
  get "workers/search_owner" => "workers#search_owner"

  # ログアウトする。workerでもownerでも処理は同じであるため、
  # workersコントローラのアクションを使う
  post "logout" => "workers#logout"

  resources :workers, only: [:show, :new, :create, :edit, :update, :destroy]



  # ownerに関するルーティング
  get "owners/top" => "owners#top"

  # ログインフォームとログイン処理
  get "owners/login" => "owners#login_form"
  post "owners/login" => "owners#login"

  resources :owners, only: [:show, :new, :create, :edit, :update, :destroy]


  # owner_workersに関するルーティング
  get "owner_workers" => "owner_workers#index"
  post "owner_workers/create/:request_id" => "owner_workers#create"
  post "owner_workers/:id/destroy" => "owner_workers#destroy"


  # 従業員から管理者に対するユーザー紐づけリクエスト"request"
  # に関するルーティング
  get "requests" => "requests#index"
  post "requests/:owner_id" => "requests#create"
  post "requests/:id/destroy" => "requests#destroy"

end

app/models/worker.rb
class Worker < ApplicationRecord
  has_secure_password

  has_many :owner_workers, dependent: :destroy
  has_many :owners, through: :owner_workers

  has_many :entries, dependent: :destroy
  has_many :requests, dependent: :destroy

  validates :name, {presence: true, length: {maximum: 14}}
  validates :email, {presence: true, uniqueness: true,
                     length: {maximum: 254}}
  validates :userid, {presence: true,
                      uniqueness: true,
                      length: {minimum: 4, maximum: 16}}
end

app/controllers/workers_controller.rb
class WorkersController < ApplicationController
  before_action :authenticate_user, {only: [:show, :edit, :update, :destroy]}
  before_action :forbid_login_user, {only: [:top, :new, :create, :login_form, :login]}
  before_action :ensure_correct_worker, {only: [:show, :edit, :update, :destroy]}

  def top
  end

  def show
    @worker = Worker.find(params[:id])
  end

  def new
    @worker = Worker.new
  end

  def create
    @worker = Worker.new(worker_params)
    if @worker.save
      # アカウント作成が成功したらそのままログイン状態にする。
      session[:user_id] = @worker.id
      session[:user_type] = "worker"

      # フラッシュメッセージを表示する。
      flash[:notice] = "アカウントを作成しました"

      # ユーザーページへリダイレクトする。
      redirect_to(@worker)
    else
      # 失敗すると再度登録フォームを表示する。
      render("workers/new")
    end
  end

  def edit
    @worker = Worker.find(params[:id])
    @edit_password_message = "パスワードを変更する方は以下に新しいパスワードを入力"
  end

  def update
    @worker = Worker.find(params[:id])

    if @worker.update(worker_params)
      flash[:notice] = "ユーザー情報を編集しました"
      redirect_to(@worker)
    else
      render("workers/edit")
    end
  end

  def login_form
  end

  def login
    # 従業員データの中から、ユーザーIDが一致するものを探す。
    @worker = Worker.find_by(userid: params[:userid])

    if @worker && @worker.authenticate(params[:password])
      # ログイン状態にする。
      session[:user_id] = @worker.id
      session[:user_type] = "worker"

      # フラッシュメッセージを表示する。
      flash[:notice] = "ログインしました"

      # ユーザーページへリダイレクトする。
      redirect_to(tasks_path)
    else
      @error_message = "ユーザーIDまたはパスワードが間違っています"
      render("workers/login_form")
    end
  end

  def logout
    session[:user_id] = nil
    session[:user_type] = nil
    flash[:notice] = "ログアウトしました"
    redirect_to("/")
  end

  def search_owner
    @owner = Owner.find_by(userid: params[:userid])
  end

  def destroy
    @worker = Worker.find(params[:id])
    @worker.destroy
    flash[:notice] = "アカウントを削除しました"
    redirect_to("/")
  end

  private
  def worker_params
    params.require(:worker).permit(:name, :userid, :email, :password, :password_confirmation)
  end

  def ensure_correct_worker
    if !(@current_user.class == Worker && @current_user.id == params[:id].to_i)
      flash[:notice] = "権限がありません"
      redirect_to("/")
    end
  end
end

app/helpers/workers_helper.rb
module WorkersHelper
end

app/views/workers/_form.html.erb
<div class="form-error">
  <% @worker.errors.full_messages.each do |message| %>
    <%= message %><br>
  <% end %>
</div>

<div class="form-wrapper">
  <%= form_with(model: @worker, local: true) do |form| %>
    <p>名前</p>
    <%= form.text_field :name %><br>

    <p>ユーザーID（4文字以上16文字以内）</p>
    <%= form.text_field :userid %><br>

    <p>メールアドレス</p>
    <%= form.email_field :email %><br>

    <!-- フォームがeditに使われる時だけ表示するメッセージ -->
    <% if @edit_password_message %>
      <br><p><%= @edit_password_message %></p>
    <% end %>

    <p>パスワード</p>
    <%= form.password_field :password %><br>

    <p>パスワード（確認）</p>
    <%= form.password_field :password_confirmation %><br>

    <%= form.submit "決定", class: "btn form-btn" %>
  <% end %>
</div>

app/views/workers/edit.html.erb
<div class="main">
  <div class="container">
    <div class="heading">
      ユーザー情報の編集
    </div>
    <%= render("form") %>
    <%= link_to("戻る", worker_path(@worker), {class: "btn return-btn"}) %>
  </div>
</div>

app/views/workers/login_form.html.erb
<div class="main">
  <div class="container">
    <div class="heading">
      ログイン（従業員）
    </div>
    <% if @error_message %>
    <div class="form-error">
      <%= @error_message %>
    </div>
    <% end %>
    <div class="form-wrapper">
      <%= form_with(url: "/workers/login", local: true) do |form| %>
        <p>ユーザーID</p>
        <%= form.text_field :userid %><br>

        <p>パスワード</p>
        <%= form.password_field :password %><br>

        <%= form.submit "ログイン", class: "btn form-btn" %>
      <% end %>
    </div>
    <%= link_to("戻る", "/workers/top", {class: "btn return-btn"}) %>
  </div>
</div>

app/views/workers/new.html.erb
<div class="main">
  <div class="container">
    <div class="heading">
      アカウント作成（従業員）
    </div>
    <%= render("form") %>
    <%= link_to("戻る", "/workers/top", {class: "btn return-btn"}) %>
  </div>
</div>

app/views/workers/search_owner.html.erb
<div class="main">
  <div class="container">
    <div class="heading">
      管理者を検索
    </div>
    <% if @error_message %>
    <div class="form-error">
        <%= @error_message %>
    </div>
    <% end %>
    <div class="form-wrapper">
      <%= form_tag("/workers/search_owner", method: :get) do %>
        <p>ユーザーＩＤ</p>
        <%= text_field_tag :userid %><br>
        <%= submit_tag "検索", class: "btn form-btn" %>
      <% end %>
    </div>
    <div class="second-heading">
      検索結果
    </div>
    <div class="owner-worker-wrapper">
      <% if @owner %>
      <table>
        <tr>
          <th>名前</th>
          <th>ユーザーＩＤ</th>
          <th></th>
        </tr>
        <tr>
          <td><%= @owner.name %></td>
          <td><%= @owner.userid %></td>
          <td><%= link_to("登録リクエストを送る", "/requests/#{@owner.id}",
                      method: :post,
                      data: { confirm: "リクエストを送信します。" }) %></td>
        </tr>
      </table>
      <% else %>
        <p>見つかるとここに表示されます</p>
      <% end %>
    </div>
  </div>
</div>

app/views/workers/show.html.erb
<div class="main">
  <div class="container">
    <div class="heading">
      マイページ
    </div>
    <div class="mypage-wrapper">
      <p>名前：<%= @worker.name %></p>
      <p>ユーザーID：<%= @worker.userid %></p>
      <p>メールアドレス：<%= @worker.email %></p>
    </div>
    <div class="edit-profile-btn-wrapper">
      <%= link_to("ユーザー情報の編集", edit_worker_path(@worker), {class: "btn edit-profile-btn"}) %>
      <%= link_to("退会する", worker_path(@worker), method: :delete,
                  data: {confirm: "退会すると、シフトのデータは削除されます。よろしいですか？"},
                  class: "btn edit-profile-btn") %>
    </div>
  </div>
</div>

app/views/workers/top.html.erb
<div class="main">
  <div class="container">
    <div class="heading">
      従業員
    </div>
    <div class="entrance-wrapper">
      <ul class="top-btns">
        <li><%= link_to("アカウント作成", new_worker_path, {class: "btn large-btn"}) %></li>
        <li><%= link_to("ログイン", "/workers/login", {class: "btn large-btn"}) %></li>
        <li><%= link_to("TOPへ戻る", "/", {class: "btn large-btn"}) %></li>
      </ul>
    </div>
  </div>
</div>