config/routes.rb
Rails.application.routes.draw do
  get "/" => "home#top"

  resources :tasks do
    resources :entries, only: [:new, :create, :edit, :update]
  end


  # workerに関するルーティング
  get "workers/top" => "workers#top"

  # ログインフォームとログイン処理
  get "workers/login" => "workers#login_form"
  post "workers/login" => "workers#login"

  # 従業員側から、シフトのやり取りをする管理者を検索し、紐づけできるように
  # するため、管理者検索フォームを実装する
  get "workers/search_owner" => "workers#search_owner"

  # ログアウトする。workerでもownerでも処理は同じであるため、
  # workersコントローラのアクションを使う
  post "logout" => "workers#logout"

  resources :workers, only: [:show, :new, :create, :edit, :update, :destroy]



  # ownerに関するルーティング
  get "owners/top" => "owners#top"

  # ログインフォームとログイン処理
  get "owners/login" => "owners#login_form"
  post "owners/login" => "owners#login"

  resources :owners, only: [:show, :new, :create, :edit, :update, :destroy]


  # owner_workersに関するルーティング
  get "owner_workers" => "owner_workers#index"
  post "owner_workers/create/:request_id" => "owner_workers#create"
  post "owner_workers/:id/destroy" => "owner_workers#destroy"


  # 従業員から管理者に対するユーザー紐づけリクエスト"request"
  # に関するルーティング
  get "requests" => "requests#index"
  post "requests/:owner_id" => "requests#create"
  post "requests/:id/destroy" => "requests#destroy"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SHIFT POST</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header>
      <div class="container">
        <div class="header-top">
          <div class="top-left">
            <%= link_to("", "/", class: "logo") %>
          </div>
          <% if @current_user %>
            <div class="top-right">
              <p>ようこそ、<%= "#{@current_user.name}（#{(@current_user.class == Worker)? "従業員" : "管理者"}）" %></p>
            </div>
          <% end %>
        </div>
        <div class="header-menu">
          <% if @current_user %>
            <% if @current_user.class == Worker %>
              <ul>
                <!-- 横並びにしたときに隙間が生まれないようにするための記述方法 -->
                <li><%= link_to("マイページ", worker_path(@current_user)) %></li><li>
                    <%= link_to("募集中一覧", tasks_path) %></li><li>
                    <%= link_to("所属一覧", "/owner_workers") %></li><li>
                    <%= link_to("管理者を検索", "/workers/search_owner") %></li><li>
                    <%= link_to("ログアウト", "/logout", {method: :post}) %></li>
              </ul>
            <% elsif @current_user.class == Owner %>
              <ul>
                <li><%= link_to("マイページ", owner_path(@current_user)) %></li><li>
                    <%= link_to("募集中一覧", tasks_path) %></li><li>
                    <%= link_to("従業員一覧", "/owner_workers") %></li><li>
                    <%= link_to("追加リクエスト", "/requests") %></li><li>
                    <%= link_to("ログアウト", "/logout", {method: :post}) %></li>
              </ul>
            <% end %>
          <% else %>
            <p>オンラインでシフト希望の提出ができます</p>
          <% end %>
        </div>
      </div>
    </header>
    <% if flash[:notice] %>
      <div class="flash">
        <%= flash[:notice] %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>